# Matrix

<p>
<ol>
<li> Create a 6x5 random matrix (matrix A) using a normal distribution with mean = -1.2 and std = .4 </li>
<li> Create another 5x3 matrix in the following format: (matrix B) 
<br>
<br>
<div>
<table style="width:200px; border:1px solid black">
<tr>
    <td style="text-align:center; border:1px solid black">0</td>
    <td style="text-align:center; border:1px solid black">-1</td>
    <td style="text-align:center; border:1px solid black">-1</td>
</tr>
<tr>
    <td style="text-align:center; border:1px solid black">3</td>
    <td style="text-align:center;border:1px solid black">4</td>
    <td style="text-align:center;border:1px solid black">1</td>
</tr>
<tr>
    <td style="text-align:center; border:1px solid black">-1</td>
    <td style="text-align:center; border:1px solid black">2</td>
    <td style="text-align:center;border:1px solid black">3</td>
</tr>
<tr>
    <td style="text-align:center; border:1px solid black">2</td>
    <td style="text-align:center; border:1px solid black">4</td>
    <td style="text-align:center; border:1px solid black">3</td>
</tr>
<tr>
    <td style="text-align:center;border:1px solid black">2</td>
    <td style="text-align:center;border:1px solid black">0</td>
    <td style="text-align:center;border:1px solid black">-2</td>
</tr>
</table>
<div></li>
<br>   
<li> Find Dot Product of matrix A and B and put it in matrix C.</li>
<li> Find the row wise sum of the matrix C.</li> 
</p>



### Part 1

In [7]:
import numpy as np
A=np.random.normal(loc=-1.2,scale=0.4,size=(6,5))
A

array([[-0.89819943, -1.61409818, -0.72422664, -0.31444844, -0.5161676 ],
       [-1.18507776, -1.13609517, -1.42633304, -1.17905114, -0.98505875],
       [-0.96496412, -0.38786345, -1.07616504, -0.97645118, -2.09392173],
       [-0.99312558, -1.1155264 , -1.65874839, -1.51065266, -0.70097789],
       [-0.89025118, -1.1299593 , -1.79808998, -1.35188371, -1.14082107],
       [-0.97294108, -0.49634388, -0.69832547, -0.27685963, -1.47741155]])

### Part 2

In [9]:
B = np.array([
    [0,-1,-1],
    [3, 4, 1],
    [-1,2, 3],
    [2, 4, 3],
    [2, 0,-2]
])
B

array([[ 0, -1, -1],
       [ 3,  4,  1],
       [-1,  2,  3],
       [ 2,  4,  3],
       [ 2,  0, -2]])

### Part 3

In [11]:
C=np.dot(A,B)
C

array([[ -5.77929996,  -8.26444029,  -2.79958877],
       [ -6.31017224, -10.92817353,  -5.79705243],
       [ -6.22817114,  -6.64462449,  -1.39290453],
       [ -6.11109192, -12.82908743,  -8.22864817],
       [ -6.57719748, -12.63330081,  -7.40798704],
       [ -4.29924853,  -3.5165239 ,   0.505865  ]])

### Part 4

In [13]:
np.sum(C,axis=1)

array([-16.84332901, -23.0353982 , -14.26570016, -27.16882751,
       -26.61848534,  -7.30990742])